CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "email" VARCHAR NOT NULL,
  "hashed_password" VARCHAR,
  "is_active" BOOLEAN NOT NULL,
  "role" userrole NOT NULL,
  "preferred_language" languagecode NOT NULL DEFAULT 'en'
);

CREATE TABLE "language" (
  "code" languagecode PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "native_name" VARCHAR NOT NULL,
  "is_active" BOOLEAN NOT NULL
);

CREATE TABLE "customerprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" "VARCHAR(20)" NOT NULL,
  "date_of_birth" DATE,
  "gender" VARCHAR
);

CREATE TABLE "adminprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" "VARCHAR(20)" NOT NULL,
  "employee_code" VARCHAR,
  "department" VARCHAR
);

CREATE TABLE "sellerprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" "VARCHAR(20)" NOT NULL,
  "business_name" VARCHAR NOT NULL,
  "gst_number" VARCHAR,
  "fssai_license" VARCHAR,
  "bank_account_number" VARCHAR NOT NULL,
  "bank_ifsc" VARCHAR NOT NULL,
  "verification_status" verificationstatus NOT NULL,
  "rejection_reason" VARCHAR,
  "business_address_id" INTEGER NOT NULL
);

CREATE TABLE "address" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "address_line1" "VARCHAR(120)" NOT NULL,
  "address_line2" "VARCHAR(120)",
  "landmark" "VARCHAR(120)",
  "city" "VARCHAR(80)" NOT NULL,
  "state" "VARCHAR(80)" NOT NULL,
  "pincode" "VARCHAR(10)" NOT NULL,
  "country" "VARCHAR(60)" NOT NULL,
  "latitude" "DOUBLEPRECISION",
  "longitude" "DOUBLEPRECISION"
);

CREATE TABLE "customeraddress" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "address_id" INTEGER NOT NULL,
  "label" VARCHAR,
  "is_default" BOOLEAN NOT NULL
);

CREATE TABLE "service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "slug" VARCHAR NOT NULL,
  "icon_url" VARCHAR,
  "is_active" BOOLEAN NOT NULL,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "service_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" INTEGER NOT NULL,
  "language_code" languagecode NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "service_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "category_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" INTEGER NOT NULL,
  "language_code" languagecode NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "subcategory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "category_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "subcategory_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subcategory_id" INTEGER NOT NULL,
  "language_code" languagecode NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "masterproduct" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "subcategory_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "image_url" VARCHAR
);

CREATE TABLE "masterproduct_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "master_product_id" INTEGER NOT NULL,
  "language_code" languagecode NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR NOT NULL
);

CREATE TABLE "store" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "name" VARCHAR NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "seller_profile_id" INTEGER NOT NULL,
  "address_id" INTEGER NOT NULL
);

CREATE TABLE "storeinventory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "store_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "price" "DOUBLEPRECISION" NOT NULL,
  "stock" INTEGER NOT NULL,
  "is_available" BOOLEAN NOT NULL
);

CREATE TABLE "cart" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL
);

CREATE TABLE "cartitem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "inventory_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "delivery_address_id" INTEGER NOT NULL,
  "status" orderstatus NOT NULL,
  "subtotal" "DOUBLEPRECISION" NOT NULL,
  "delivery_fee" "DOUBLEPRECISION" NOT NULL,
  "tax" "DOUBLEPRECISION" NOT NULL,
  "total" "DOUBLEPRECISION" NOT NULL,
  "placed_at" "TIMESTAMPTZ" NOT NULL
);

CREATE TABLE "orderitem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "order_id" INTEGER NOT NULL,
  "inventory_id" INTEGER NOT NULL,
  "product_name_snapshot" VARCHAR NOT NULL,
  "unit_price_snapshot" "DOUBLEPRECISION" NOT NULL,
  "quantity" INTEGER NOT NULL,
  "line_total" "DOUBLEPRECISION" NOT NULL
);

CREATE TABLE "payment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "order_id" INTEGER NOT NULL,
  "amount" "DOUBLEPRECISION" NOT NULL,
  "method" paymentmethod NOT NULL,
  "status" paymentstatus NOT NULL,
  "gateway_txn_id" VARCHAR,
  "paid_at" "TIMESTAMPTZ"
);

CREATE TABLE "delivery" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "order_id" INTEGER NOT NULL,
  "status" deliverystatus NOT NULL,
  "packed_at" "TIMESTAMPTZ",
  "dispatched_at" "TIMESTAMPTZ",
  "delivered_at" "TIMESTAMPTZ",
  "tracking_notes" VARCHAR
);

CREATE TABLE "review" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "updated_at" "TIMESTAMPTZ" NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "product_id" INTEGER,
  "store_id" INTEGER,
  "order_id" INTEGER,
  "rating" INTEGER NOT NULL,
  "comment" VARCHAR
);

CREATE TABLE "favorite" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" "TIMESTAMPTZ" NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL
);

CREATE UNIQUE INDEX "ix_user_email" ON "user" ("email");

CREATE UNIQUE INDEX "ix_customerprofile_user" ON "customerprofile" ("user_id");

CREATE UNIQUE INDEX "ix_customerprofile_phone" ON "customerprofile" ("phone");

CREATE UNIQUE INDEX "ix_adminprofile_user" ON "adminprofile" ("user_id");

CREATE UNIQUE INDEX "ix_adminprofile_empcode" ON "adminprofile" ("employee_code");

CREATE UNIQUE INDEX "ix_adminprofile_phone" ON "adminprofile" ("phone");

CREATE UNIQUE INDEX ON "sellerprofile" ("user_id");

CREATE UNIQUE INDEX "ix_sellerprofile_phone" ON "sellerprofile" ("phone");

CREATE INDEX "ix_sellerprofile_address" ON "sellerprofile" ("business_address_id");

CREATE UNIQUE INDEX "uq_customeraddress_customer_address" ON "customeraddress" ("customer_profile_id", "address_id");

CREATE INDEX "ix_customeraddress_customer" ON "customeraddress" ("customer_profile_id");

CREATE UNIQUE INDEX "ix_service_slug" ON "service" ("slug");

CREATE UNIQUE INDEX "uq_service_translation" ON "service_translation" ("service_id", "language_code");

CREATE UNIQUE INDEX "uq_category_service_slug" ON "category" ("service_id", "slug");

CREATE INDEX "ix_category_service" ON "category" ("service_id");

CREATE UNIQUE INDEX "uq_category_translation" ON "category_translation" ("category_id", "language_code");

CREATE UNIQUE INDEX "uq_subcategory_category_slug" ON "subcategory" ("category_id", "slug");

CREATE INDEX "ix_subcategory_category" ON "subcategory" ("category_id");

CREATE UNIQUE INDEX "uq_subcategory_translation" ON "subcategory_translation" ("subcategory_id", "language_code");

CREATE UNIQUE INDEX "ix_masterproduct_slug" ON "masterproduct" ("slug");

CREATE INDEX "ix_masterproduct_subcategory" ON "masterproduct" ("subcategory_id");

CREATE UNIQUE INDEX "uq_masterproduct_translation" ON "masterproduct_translation" ("master_product_id", "language_code");

CREATE INDEX "ix_store_name" ON "store" ("name");

CREATE INDEX "ix_store_seller" ON "store" ("seller_profile_id");

CREATE INDEX "ix_store_address" ON "store" ("address_id");

CREATE UNIQUE INDEX "uq_store_product" ON "storeinventory" ("store_id", "product_id");

CREATE UNIQUE INDEX "uq_cart_customer_store" ON "cart" ("customer_profile_id", "store_id");

CREATE UNIQUE INDEX "uq_cartitem_cart_inventory" ON "cartitem" ("cart_id", "inventory_id");

CREATE INDEX "ix_order_customer" ON "order" ("customer_profile_id");

CREATE INDEX "ix_order_store" ON "order" ("store_id");

CREATE INDEX "ix_order_status" ON "order" ("status");

CREATE UNIQUE INDEX "uq_orderitem_order_inventory" ON "orderitem" ("order_id", "inventory_id");

CREATE INDEX "ix_payment_order" ON "payment" ("order_id");

CREATE UNIQUE INDEX "ix_payment_gateway_txn" ON "payment" ("gateway_txn_id");

CREATE UNIQUE INDEX "ix_delivery_order" ON "delivery" ("order_id");

CREATE INDEX "ix_review_product" ON "review" ("product_id");

CREATE INDEX "ix_review_store" ON "review" ("store_id");

CREATE INDEX "ix_review_customer" ON "review" ("customer_profile_id");

CREATE UNIQUE INDEX "uq_favorite_customer_product" ON "favorite" ("customer_profile_id", "product_id");

COMMENT ON TABLE "language" IS 'Seed: en/English/English, hi/Hindi/हिन्दी, mr/Marathi/मराठी, gu/Gujarati/ગુજરાતી, pa/Punjabi/ਪੰਜਾਬੀ. languagecode enum: en, hi, mr, gu, pa.';

COMMENT ON TABLE "customeraddress" IS 'Partial unique index: CREATE UNIQUE INDEX uq_customeraddress_one_default ON customeraddress (customer_profile_id) WHERE is_default = true';

COMMENT ON TABLE "service" IS 'Top-level vertical: Groceries, Pharmacy, Restaurant, etc. Display name/description live in service_translation.';

COMMENT ON TABLE "order" IS 'Totals are intentionally denormalized for immutable financial history.';

COMMENT ON TABLE "review" IS 'CHECK ((product_id IS NOT NULL) != (store_id IS NOT NULL))';

ALTER TABLE "customerprofile" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "adminprofile" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sellerprofile" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user" ADD FOREIGN KEY ("preferred_language") REFERENCES "language" ("code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "service_translation" ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "category_translation" ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "subcategory_translation" ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "masterproduct_translation" ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sellerprofile" ADD FOREIGN KEY ("business_address_id") REFERENCES "address" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "store" ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order" ADD FOREIGN KEY ("delivery_address_id") REFERENCES "address" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customeraddress" ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customeraddress" ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "category" ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "subcategory" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "masterproduct" ADD FOREIGN KEY ("subcategory_id") REFERENCES "subcategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "service_translation" ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "category_translation" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "subcategory_translation" ADD FOREIGN KEY ("subcategory_id") REFERENCES "subcategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "masterproduct_translation" ADD FOREIGN KEY ("master_product_id") REFERENCES "masterproduct" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "store" ADD FOREIGN KEY ("seller_profile_id") REFERENCES "sellerprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "storeinventory" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "storeinventory" ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart" ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cartitem" ADD FOREIGN KEY ("cart_id") REFERENCES "cart" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cartitem" ADD FOREIGN KEY ("inventory_id") REFERENCES "storeinventory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order" ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orderitem" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orderitem" ADD FOREIGN KEY ("inventory_id") REFERENCES "storeinventory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "delivery" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "review" ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "review" ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "review" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "review" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorite" ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorite" ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id") DEFERRABLE INITIALLY IMMEDIATE;
