-- KhanaBazaar database schema (Postgres)
-- Source of truth: SQLModel models in backend/app/src/app/models/ + Alembic
-- migration head `cecb3aa39b17`. Regenerate this file when the head changes.
--
-- Enums (created via Alembic migrations):
--   userrole          : 'Customer', 'Seller', 'Admin'
--   verificationstatus: 'Pending', 'Approved', 'Rejected'
--   orderstatus       : 'Pending', 'Paid', 'Packed', 'Dispatched', 'Delivered', 'Cancelled'
--   paymentmethod     : 'Upi', 'Cash'
--   paymentstatus     : 'Pending', 'Paid', 'Failed', 'Refunded'
--   deliverystatus    : 'Pending', 'Packed', 'Dispatched', 'Delivered', 'Cancelled'
--   locationsource    : 'manual', 'autocomplete', 'pin', 'geocoded'
--
-- PostGIS extension is required (CREATE EXTENSION IF NOT EXISTS postgis).
-- `language.code` is plain VARCHAR (PK); the LanguageCode Python enum
-- (en/hi/mr/gu/pa) is enforced at the application layer, not the DB.

CREATE TABLE "language" (
  "code" VARCHAR PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "native_name" VARCHAR NOT NULL,
  "is_active" BOOLEAN NOT NULL
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "email" VARCHAR NOT NULL,
  "hashed_password" VARCHAR,
  "is_active" BOOLEAN NOT NULL,
  "role" userrole NOT NULL,
  "preferred_language" VARCHAR NOT NULL DEFAULT 'en'
);

CREATE TABLE "address" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "address_line1" VARCHAR(120) NOT NULL,
  "address_line2" VARCHAR(120),
  "landmark" VARCHAR(120),
  "city" VARCHAR(80) NOT NULL,
  "state" VARCHAR(80) NOT NULL,
  "pincode" VARCHAR(10) NOT NULL,
  "country" VARCHAR(60) NOT NULL DEFAULT 'India',
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "digipin" VARCHAR(12),
  "place_id" VARCHAR(255),
  "location_source" locationsource,
  -- `geo` is a GENERATED STORED column added by migration 3e36788adecf.
  -- Not declared on the SQLModel; reads happen via raw SQL.
  "geo" geography(Point, 4326) GENERATED ALWAYS AS (
    CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL
         THEN ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
         ELSE NULL END
  ) STORED
);

CREATE TABLE "customerprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" VARCHAR(20),
  "date_of_birth" DATE,
  "gender" VARCHAR
);

CREATE TABLE "adminprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" VARCHAR(20),
  "employee_code" VARCHAR UNIQUE,
  "department" VARCHAR
);

CREATE TABLE "sellerprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" VARCHAR(20) NOT NULL,
  "business_name" VARCHAR NOT NULL,
  "gst_number" VARCHAR,
  "fssai_license" VARCHAR,
  "bank_account_number" VARCHAR,
  "bank_ifsc" VARCHAR,
  "verification_status" verificationstatus NOT NULL,
  "rejection_reason" VARCHAR,
  "business_address_id" INTEGER NOT NULL
);

CREATE TABLE "customeraddress" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "address_id" INTEGER NOT NULL,
  "label" VARCHAR,
  "is_default" BOOLEAN NOT NULL
);

CREATE TABLE "service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "slug" VARCHAR NOT NULL,
  "icon_url" VARCHAR,
  "is_active" BOOLEAN NOT NULL,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "service_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "service_id" INTEGER NOT NULL,
  "language_code" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "sellerprofile_service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "seller_profile_id" INTEGER NOT NULL,
  "service_id" INTEGER NOT NULL
);

CREATE TABLE "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "service_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "category_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "category_id" INTEGER NOT NULL,
  "language_code" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "subcategory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "category_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "subcategory_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "subcategory_id" INTEGER NOT NULL,
  "language_code" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "masterproduct" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "subcategory_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "image_url" VARCHAR,
  "base_price" DOUBLE PRECISION NOT NULL
);

CREATE TABLE "masterproduct_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "master_product_id" INTEGER NOT NULL,
  "language_code" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR NOT NULL
);

CREATE TABLE "store" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "name" VARCHAR NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "seller_profile_id" INTEGER NOT NULL,
  "address_id" INTEGER NOT NULL,
  "delivery_radius_km" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
  "pin_confirmed" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "storeinventory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "store_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "stock" INTEGER NOT NULL,
  "is_available" BOOLEAN NOT NULL
);

CREATE TABLE "cart" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL
);

CREATE TABLE "cartitem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "inventory_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "delivery_address_id" INTEGER NOT NULL,
  "status" orderstatus NOT NULL,
  "subtotal" DOUBLE PRECISION NOT NULL,
  "delivery_fee" DOUBLE PRECISION NOT NULL,
  "tax" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "delivery_address_snapshot" VARCHAR NOT NULL,
  "placed_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "orderitem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "order_id" INTEGER NOT NULL,
  "inventory_id" INTEGER,
  "product_name_snapshot" VARCHAR NOT NULL,
  "unit_price_snapshot" DOUBLE PRECISION NOT NULL,
  "quantity" INTEGER NOT NULL,
  "line_total" DOUBLE PRECISION NOT NULL
);

CREATE TABLE "payment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "order_id" INTEGER NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "method" paymentmethod NOT NULL,
  "status" paymentstatus NOT NULL,
  "gateway_txn_id" VARCHAR,
  "paid_at" TIMESTAMPTZ
);

CREATE TABLE "delivery" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "order_id" INTEGER NOT NULL,
  "status" deliverystatus NOT NULL,
  "packed_at" TIMESTAMPTZ,
  "dispatched_at" TIMESTAMPTZ,
  "delivered_at" TIMESTAMPTZ,
  "tracking_notes" VARCHAR
);

CREATE TABLE "review" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "product_id" INTEGER,
  "store_id" INTEGER,
  "order_id" INTEGER,
  "rating" INTEGER NOT NULL,
  "comment" VARCHAR,
  CONSTRAINT "ck_review_one_target"
    CHECK ((product_id IS NOT NULL) != (store_id IS NOT NULL)),
  CONSTRAINT "ck_review_rating_range"
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE "favorite" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL
);

-- Indexes -----------------------------------------------------------------

CREATE UNIQUE INDEX "ix_user_email" ON "user" ("email");

CREATE UNIQUE INDEX "ix_customerprofile_user" ON "customerprofile" ("user_id");
CREATE UNIQUE INDEX "ix_customerprofile_phone" ON "customerprofile" ("phone");

CREATE UNIQUE INDEX "ix_adminprofile_user" ON "adminprofile" ("user_id");
CREATE UNIQUE INDEX "ix_adminprofile_phone" ON "adminprofile" ("phone");

CREATE UNIQUE INDEX "uq_sellerprofile_user" ON "sellerprofile" ("user_id");
CREATE UNIQUE INDEX "ix_sellerprofile_phone" ON "sellerprofile" ("phone");
CREATE INDEX "ix_sellerprofile_business_address_id"
  ON "sellerprofile" ("business_address_id");

CREATE UNIQUE INDEX "uq_sellerprofile_service"
  ON "sellerprofile_service" ("seller_profile_id", "service_id");
CREATE INDEX "ix_sellerprofile_service_seller_profile_id"
  ON "sellerprofile_service" ("seller_profile_id");
CREATE INDEX "ix_sellerprofile_service_service_id"
  ON "sellerprofile_service" ("service_id");

CREATE UNIQUE INDEX "uq_customeraddress_customer_address"
  ON "customeraddress" ("customer_profile_id", "address_id");
CREATE INDEX "ix_customeraddress_customer_profile_id"
  ON "customeraddress" ("customer_profile_id");
-- Partial unique index: only one default address per customer.
CREATE UNIQUE INDEX "uq_customeraddress_one_default"
  ON "customeraddress" ("customer_profile_id")
  WHERE is_default = true;

CREATE INDEX "ix_address_geo" ON "address" USING GIST ("geo");

CREATE UNIQUE INDEX "ix_service_slug" ON "service" ("slug");
CREATE UNIQUE INDEX "uq_service_translation"
  ON "service_translation" ("service_id", "language_code");

CREATE UNIQUE INDEX "uq_category_service_slug" ON "category" ("service_id", "slug");
CREATE INDEX "ix_category_service_id" ON "category" ("service_id");
CREATE UNIQUE INDEX "uq_category_translation"
  ON "category_translation" ("category_id", "language_code");

CREATE UNIQUE INDEX "uq_subcategory_category_slug"
  ON "subcategory" ("category_id", "slug");
CREATE INDEX "ix_subcategory_category_id" ON "subcategory" ("category_id");
CREATE UNIQUE INDEX "uq_subcategory_translation"
  ON "subcategory_translation" ("subcategory_id", "language_code");

CREATE UNIQUE INDEX "ix_masterproduct_slug" ON "masterproduct" ("slug");
CREATE INDEX "ix_masterproduct_subcategory_id" ON "masterproduct" ("subcategory_id");
CREATE UNIQUE INDEX "uq_masterproduct_translation"
  ON "masterproduct_translation" ("master_product_id", "language_code");

CREATE UNIQUE INDEX "uq_store_seller_profile" ON "store" ("seller_profile_id");
CREATE INDEX "ix_store_name" ON "store" ("name");
CREATE INDEX "ix_store_seller_profile_id" ON "store" ("seller_profile_id");
CREATE INDEX "ix_store_address_id" ON "store" ("address_id");

CREATE UNIQUE INDEX "uq_store_product" ON "storeinventory" ("store_id", "product_id");

CREATE UNIQUE INDEX "uq_cart_customer_store" ON "cart" ("customer_profile_id", "store_id");
CREATE UNIQUE INDEX "uq_cartitem_cart_inventory" ON "cartitem" ("cart_id", "inventory_id");

CREATE INDEX "ix_order_customer_profile_id" ON "order" ("customer_profile_id");
CREATE INDEX "ix_order_store_id" ON "order" ("store_id");
CREATE INDEX "ix_order_status" ON "order" ("status");

CREATE UNIQUE INDEX "uq_orderitem_order_inventory"
  ON "orderitem" ("order_id", "inventory_id");

CREATE INDEX "ix_payment_order_id" ON "payment" ("order_id");
CREATE UNIQUE INDEX "ix_payment_gateway_txn_id" ON "payment" ("gateway_txn_id");

CREATE UNIQUE INDEX "ix_delivery_order_id" ON "delivery" ("order_id");

CREATE INDEX "ix_review_customer_profile_id" ON "review" ("customer_profile_id");
CREATE INDEX "ix_review_product_id" ON "review" ("product_id");
CREATE INDEX "ix_review_store_id" ON "review" ("store_id");

CREATE UNIQUE INDEX "uq_favorite_customer_product"
  ON "favorite" ("customer_profile_id", "product_id");

-- Comments ----------------------------------------------------------------

COMMENT ON TABLE "language" IS
  'Seed: en/English/English, hi/Hindi/हिन्दी, mr/Marathi/मराठी, gu/Gujarati/ગુજરાતી, pa/Punjabi/ਪੰਜਾਬੀ. LanguageCode app-enum: en, hi, mr, gu, pa.';

COMMENT ON TABLE "customeraddress" IS
  'Partial unique index uq_customeraddress_one_default enforces one default address per customer (WHERE is_default = true).';

COMMENT ON TABLE "service" IS
  'Top-level vertical: Groceries, Pharmacy, Restaurant, etc. Display name/description live in service_translation.';

COMMENT ON TABLE "sellerprofile_service" IS
  'M:N junction: seller offers one or more services. Replaces the dropped sellerprofile.business_category column.';

COMMENT ON COLUMN "address"."geo" IS
  'Generated STORED geography(Point, 4326) column derived from latitude/longitude. SQLModel does not declare it; reads happen via raw SQL. Indexed by GiST (ix_address_geo).';

COMMENT ON TABLE "store" IS
  'pin_confirmed=false until seller confirms the map pin in the dashboard. delivery_radius_km gates serviceability checks (PostGIS ST_DWithin).';

COMMENT ON TABLE "order" IS
  'Totals are intentionally denormalized for immutable financial history. delivery_address_snapshot captures a human-readable copy of the address at order time.';

COMMENT ON TABLE "review" IS
  'CHECK ck_review_one_target: exactly one of product_id / store_id must be set. CHECK ck_review_rating_range: rating in 1..5.';

-- Foreign keys ------------------------------------------------------------

ALTER TABLE "user"
  ADD FOREIGN KEY ("preferred_language") REFERENCES "language" ("code");

ALTER TABLE "customerprofile"
  ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "adminprofile"
  ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "sellerprofile"
  ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "sellerprofile"
  ADD FOREIGN KEY ("business_address_id") REFERENCES "address" ("id");

ALTER TABLE "sellerprofile_service"
  ADD FOREIGN KEY ("seller_profile_id") REFERENCES "sellerprofile" ("id");
ALTER TABLE "sellerprofile_service"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");

ALTER TABLE "customeraddress"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "customeraddress"
  ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id");

ALTER TABLE "service_translation"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");
ALTER TABLE "service_translation"
  ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code");

ALTER TABLE "category"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");
ALTER TABLE "category_translation"
  ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");
ALTER TABLE "category_translation"
  ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code");

ALTER TABLE "subcategory"
  ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");
ALTER TABLE "subcategory_translation"
  ADD FOREIGN KEY ("subcategory_id") REFERENCES "subcategory" ("id");
ALTER TABLE "subcategory_translation"
  ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code");

ALTER TABLE "masterproduct"
  ADD FOREIGN KEY ("subcategory_id") REFERENCES "subcategory" ("id");
ALTER TABLE "masterproduct_translation"
  ADD FOREIGN KEY ("master_product_id") REFERENCES "masterproduct" ("id");
ALTER TABLE "masterproduct_translation"
  ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code");

ALTER TABLE "store"
  ADD FOREIGN KEY ("seller_profile_id") REFERENCES "sellerprofile" ("id");
ALTER TABLE "store"
  ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id");

ALTER TABLE "storeinventory"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
ALTER TABLE "storeinventory"
  ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id");

ALTER TABLE "cart"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "cart"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");

ALTER TABLE "cartitem"
  ADD FOREIGN KEY ("cart_id") REFERENCES "cart" ("id");
ALTER TABLE "cartitem"
  ADD FOREIGN KEY ("inventory_id") REFERENCES "storeinventory" ("id");

ALTER TABLE "order"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "order"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
ALTER TABLE "order"
  ADD FOREIGN KEY ("delivery_address_id") REFERENCES "address" ("id");

ALTER TABLE "orderitem"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");
ALTER TABLE "orderitem"
  ADD FOREIGN KEY ("inventory_id") REFERENCES "storeinventory" ("id");

ALTER TABLE "payment"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "delivery"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "review"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "review"
  ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id");
ALTER TABLE "review"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
ALTER TABLE "review"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "favorite"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "favorite"
  ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id");
