-- Copyright (c) 2026 Rishi Mule. All Rights Reserved.
-- This code and its associated documentation cannot be copied, modified, or distributed without explicit permission from the author.
-- KhanaBazaar database schema (Postgres)
-- Source of truth: SQLModel models in backend/app/src/app/models/ + Alembic
-- migration head `932c4bd8aa24`. Regenerate this file when the head changes.
--
-- Enums (created via Alembic migrations):
--   userrole                     : 'Customer', 'Seller', 'Admin'
--   verificationstatus           : 'Pending', 'Approved', 'Rejected'
--   orderstatus                  : 'Pending', 'Paid', 'Packed', 'Dispatched', 'Delivered', 'Cancelled'
--   paymentmethod                : 'Upi', 'Cash', 'Credit', 'NetBanking', 'PayAtStore'  (Python values: 'upi', 'cash', 'credit', 'net_banking', 'pay_at_store')
--   deliverymode                 : 'DoorDelivery', 'Pickup'  (Python values: 'door_delivery', 'pickup')
--   paymentstatus                : 'Pending', 'Paid', 'Failed', 'Refunded'
--   deliverystatus               : 'Pending', 'Packed', 'Dispatched', 'Delivered', 'Cancelled'
--   locationsource               : 'manual', 'autocomplete', 'pin', 'geocoded'
--   adminactiontargettype        : 'Inventory', 'Order', 'Store', 'SellerProfile'
--   notificationtype             : 'OrderStatus', 'DeliveryOtp', 'FeeActivated', 'FeeExpiring', 'FeeSuspended', 'Referral', 'Credit', 'Announcement'  (PG value is the enum member NAME; Python values are 'order_status', 'delivery_otp', 'fee_activated', 'fee_expiring', 'fee_suspended', 'referral', 'credit', 'announcement')
--   notificationaudience         : 'customers', 'sellers', 'both'  (snake_case values)
--   campaignstatus               : 'draft', 'sending', 'sent', 'failed'  (snake_case values)
--   sellerprofilechangegroup     : 'identity', 'address', 'legal', 'banking', 'services', 'store_basics', 'avatar'
--   sellerprofilechangestatus    : 'submitted', 'changes_requested', 'approved', 'rejected', 'withdrawn'
--   sellerprofilechangeeventkind : 'submitted', 'resubmitted', 'changes_requested', 'approved', 'approved_with_edits', 'rejected', 'withdrawn'
--   policykind                   : 'terms', 'privacy'
--   onboardingrequeststatus      : 'new', 'contacted', 'onboarded', 'dismissed'
--   referralstatus               : 'pending_review', 'approved', 'rejected', 'active', 'expired'
--   referraltargetrole           : 'customer', 'seller'
--   creditaccountstatus          : 'active', 'suspended'
--   creditentrytype              : 'charge', 'repayment', 'reversal'
--   feemodel                     : 'freebie', 'subscription', 'order_value_percent', 'pay_per_transaction'  (PG value is the enum member VALUE, via values_callable)
--   arrangementstatus            : 'trial', 'pending_activation', 'active', 'grace', 'suspended'  (PG value is the enum member VALUE, via values_callable)
--   feepaymentkind               : 'subscription_fee', 'security_deposit', 'pay_per_txn_topup', 'order_value_invoice'  (PG value is the enum member VALUE, via values_callable)
--   feepaymentstatus             : 'pending', 'confirmed', 'rejected'  (PG value is the enum member VALUE, via values_callable)
--   feeeventtype                 : 'arrangement_created', 'model_changed', 'activated', 'extended', 'renewed', 'trial_held', 'reminder_sent', 'grace_started', 'suspended', 'reactivated', 'terminated', 'payment_recorded', 'payment_confirmed', 'payment_rejected', 'deposit_recorded', 'deposit_forfeited', 'deposit_refunded', 'balance_topup', 'balance_deducted', 'balance_refunded', 'invoice_issued', 'invoice_paid', 'invoice_waived'  (PG value is the enum member VALUE, via values_callable)
--
-- Required extensions:
--   postgis (geography column on address)
--   pg_trgm (GIN trigram indexes for slug + translation name search)
--
-- `language.code` is plain VARCHAR (PK); the LanguageCode Python enum
-- (en/hi/mr/gu/pa) is enforced at the application layer, not the DB.

CREATE TABLE "language" (
  "code" VARCHAR PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "native_name" VARCHAR NOT NULL,
  "is_active" BOOLEAN NOT NULL
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "email" VARCHAR NOT NULL,
  "hashed_password" VARCHAR,
  "is_active" BOOLEAN NOT NULL,
  "role" userrole NOT NULL,
  "preferred_language" VARCHAR NOT NULL DEFAULT 'en'
);

CREATE TABLE "address" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "address_line1" VARCHAR(120) NOT NULL,
  "address_line2" VARCHAR(120),
  "landmark" VARCHAR(120),
  "city" VARCHAR(80) NOT NULL,
  "state" VARCHAR(80) NOT NULL,
  "pincode" VARCHAR(10) NOT NULL,
  "country" VARCHAR(60) NOT NULL DEFAULT 'India',
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "digipin" VARCHAR(12),
  "place_id" VARCHAR(255),
  "location_source" locationsource,
  -- `geo` is a GENERATED STORED column added by migration 3e36788adecf.
  -- Not declared on the SQLModel; reads happen via raw SQL.
  "geo" geography(Point, 4326) GENERATED ALWAYS AS (
    CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL
         THEN ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
         ELSE NULL END
  ) STORED
);

CREATE TABLE "customerprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" VARCHAR(20),
  "date_of_birth" DATE,
  "gender" VARCHAR,
  "preferred_language" VARCHAR(8),
  "marketing_opt_in" BOOLEAN NOT NULL DEFAULT false,
  "notify_order_email" BOOLEAN NOT NULL DEFAULT true,
  "notify_order_sms" BOOLEAN NOT NULL DEFAULT false,
  "phone_verified_at" TIMESTAMPTZ,
  "avatar_url" VARCHAR,
  "avatar_storage_key" VARCHAR
);

CREATE TABLE "adminprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" VARCHAR(20),
  "employee_code" VARCHAR UNIQUE,
  "department" VARCHAR
);

CREATE TABLE "sellerprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "user_id" INTEGER NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR,
  "phone" VARCHAR(20) NOT NULL,
  "business_name" VARCHAR NOT NULL,
  "gst_number" VARCHAR,
  "fssai_license" VARCHAR,
  "bank_account_number" VARCHAR,
  "bank_ifsc" VARCHAR,
  "verification_status" verificationstatus NOT NULL,
  "rejection_reason" VARCHAR,
  "business_address_id" INTEGER NOT NULL,
  "avatar_url" VARCHAR,
  "avatar_storage_key" VARCHAR
);

CREATE TABLE "customeraddress" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "address_id" INTEGER NOT NULL,
  "label" VARCHAR,
  "is_default" BOOLEAN NOT NULL
);

CREATE TABLE "service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "slug" VARCHAR NOT NULL,
  "icon_url" VARCHAR,
  "is_active" BOOLEAN NOT NULL,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "service_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "service_id" INTEGER NOT NULL,
  "language_code" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "sellerprofile_service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "seller_profile_id" INTEGER NOT NULL,
  "service_id" INTEGER NOT NULL,
  "free_delivery_threshold" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "delivery_fee" DOUBLE PRECISION NOT NULL,
  "delivery_eta_min_minutes" INTEGER NOT NULL,
  "delivery_eta_max_minutes" INTEGER NOT NULL,
  "pickup_enabled" BOOLEAN NOT NULL DEFAULT false,
  -- Per-service pause (holiday mode); app-level model default governs new rows.
  "is_paused" BOOLEAN NOT NULL,
  "pause_reason" VARCHAR(200),
  "paused_until" DATE
);

CREATE TABLE "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "service_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "image_url" VARCHAR,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "category_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "category_id" INTEGER NOT NULL,
  "language_code" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "subcategory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "category_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "image_url" VARCHAR,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "sort_order" INTEGER NOT NULL
);

CREATE TABLE "subcategory_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "subcategory_id" INTEGER NOT NULL,
  "language_code" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR
);

CREATE TABLE "masterproduct" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "subcategory_id" INTEGER NOT NULL,
  "slug" VARCHAR NOT NULL,
  "image_url" VARCHAR,
  "base_price" DOUBLE PRECISION NOT NULL,
  "brand" VARCHAR,
  "unit" VARCHAR,
  "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "masterproduct_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "master_product_id" INTEGER NOT NULL,
  "language_code" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR NOT NULL
);

CREATE TABLE "masterproductimage" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "master_product_id" INTEGER NOT NULL,
  "position" INTEGER NOT NULL,
  "url" VARCHAR NOT NULL,
  "source" VARCHAR NOT NULL,
  "storage_key" VARCHAR
);

CREATE TABLE "store" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "name" VARCHAR NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "seller_profile_id" INTEGER NOT NULL,
  "address_id" INTEGER NOT NULL,
  "delivery_radius_km" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
  "pin_confirmed" BOOLEAN NOT NULL DEFAULT false,
  -- Store-wide pause (holiday mode); app-level model default governs new rows.
  "is_paused" BOOLEAN NOT NULL,
  "pause_reason" VARCHAR(200),
  "paused_until" DATE
);

CREATE TABLE "storeinventory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "store_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "stock" INTEGER NOT NULL,
  "is_available" BOOLEAN NOT NULL
);

CREATE TABLE "cart" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "service_id" INTEGER NOT NULL
);

CREATE TABLE "cartitem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "inventory_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL
);

CREATE TABLE "order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "service_id" INTEGER NOT NULL,
  "service_name_snapshot" VARCHAR NOT NULL,
  "delivery_address_id" INTEGER NOT NULL,
  "delivery_mode" deliverymode NOT NULL DEFAULT 'DoorDelivery',
  "status" orderstatus NOT NULL,
  "subtotal" DOUBLE PRECISION NOT NULL,
  "delivery_fee" DOUBLE PRECISION NOT NULL,
  "tax" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "delivery_address_snapshot" VARCHAR NOT NULL,
  "placed_at" TIMESTAMPTZ NOT NULL,
  -- Delivery-ETA window snapshot, frozen at order time.
  "delivery_eta_min_minutes" INTEGER NOT NULL,
  "delivery_eta_max_minutes" INTEGER NOT NULL,
  -- Optional customer-requested delivery window (soft hint; date + time-of-day band).
  "preferred_delivery_date" DATE,
  "preferred_delivery_window" VARCHAR(16)
);

CREATE TABLE "orderitem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "order_id" INTEGER NOT NULL,
  "inventory_id" INTEGER,
  "product_name_snapshot" VARCHAR NOT NULL,
  "unit_price_snapshot" DOUBLE PRECISION NOT NULL,
  "quantity" INTEGER NOT NULL,
  "line_total" DOUBLE PRECISION NOT NULL
);

CREATE TABLE "payment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "order_id" INTEGER NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "method" paymentmethod NOT NULL,
  "status" paymentstatus NOT NULL,
  "gateway_txn_id" VARCHAR,
  "paid_at" TIMESTAMPTZ
);

CREATE TABLE "delivery" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "order_id" INTEGER NOT NULL,
  "status" deliverystatus NOT NULL,
  "packed_at" TIMESTAMPTZ,
  "dispatched_at" TIMESTAMPTZ,
  "delivered_at" TIMESTAMPTZ,
  "tracking_notes" VARCHAR,
  "delivery_otp" VARCHAR(6),
  "delivery_otp_attempts" INTEGER NOT NULL DEFAULT 0,
  "delivery_otp_sent_at" TIMESTAMPTZ,
  "delivery_otp_verified_at" TIMESTAMPTZ
);

CREATE TABLE "review" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "product_id" INTEGER,
  "store_id" INTEGER,
  "order_id" INTEGER,
  "rating" INTEGER NOT NULL,
  "comment" VARCHAR,
  CONSTRAINT "ck_review_one_target"
    CHECK ((product_id IS NOT NULL) != (store_id IS NOT NULL)),
  CONSTRAINT "ck_review_rating_range"
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE "favorite" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL
);

CREATE TABLE "search_query_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "query_id" UUID NOT NULL,
  "user_id" INTEGER,
  "session_id" VARCHAR(64),
  "query" VARCHAR(100) NOT NULL,
  "locale" VARCHAR(8) NOT NULL,
  "lat" NUMERIC(9, 5),
  "lng" NUMERIC(9, 5),
  "store_id" INTEGER,
  "result_count" INTEGER NOT NULL,
  "clicked_product_id" INTEGER,
  "clicked_store_id" INTEGER,
  "clicked_position" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "admin_action_log" (
  "id" UUID PRIMARY KEY,
  "admin_user_id" INTEGER NOT NULL,
  "target_seller_id" INTEGER NOT NULL,
  "target_type" adminactiontargettype NOT NULL,
  -- No FK on target_id: deleted-row history must survive (inventory/order/etc).
  "target_id" INTEGER NOT NULL,
  "action" VARCHAR(64) NOT NULL,
  "before_json" JSONB,
  "after_json" JSONB,
  "reason" VARCHAR(500),
  "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "pushsubscription" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER NOT NULL,
  "endpoint" VARCHAR NOT NULL,
  "p256dh" VARCHAR NOT NULL,
  "auth" VARCHAR NOT NULL,
  "user_agent" VARCHAR,
  "last_seen_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "notification" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "customer_profile_id" INTEGER,
  "seller_profile_id" INTEGER,
  "order_id" INTEGER,
  "campaign_id" INTEGER REFERENCES "notification_campaign" ("id"),
  "type" notificationtype NOT NULL,
  "title" VARCHAR NOT NULL,
  "body" VARCHAR NOT NULL,
  "status_value" VARCHAR NOT NULL,
  "read" BOOLEAN NOT NULL,
  "image_url" VARCHAR(500),
  "cta_url" VARCHAR(500),
  "cta_label" VARCHAR(80),
  CONSTRAINT "ck_notification_one_recipient"
    CHECK ((customer_profile_id IS NOT NULL) <> (seller_profile_id IS NOT NULL))
);

CREATE TABLE "notification_campaign" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "audience" notificationaudience NOT NULL,
  "filters" JSONB NOT NULL,
  "channels" JSONB NOT NULL,
  "title" VARCHAR NOT NULL,
  "body" VARCHAR NOT NULL,
  "image_url" VARCHAR(500),
  "image_storage_key" VARCHAR(300),
  "cta_url" VARCHAR(500),
  "cta_label" VARCHAR(80),
  "is_essential" BOOLEAN NOT NULL DEFAULT false,
  "status" campaignstatus NOT NULL DEFAULT 'draft',
  "recipients_targeted" INTEGER NOT NULL DEFAULT 0,
  "inapp_created" INTEGER NOT NULL DEFAULT 0,
  "email_enqueued" INTEGER NOT NULL DEFAULT 0,
  "sms_enqueued" INTEGER NOT NULL DEFAULT 0,
  "created_by_admin_id" INTEGER NOT NULL REFERENCES "user" ("id"),
  "sent_at" TIMESTAMPTZ
);
CREATE INDEX "ix_notification_campaign_status"
  ON "notification_campaign" ("status");

CREATE TABLE "seller_profile_change_request" (
  "id" UUID PRIMARY KEY,
  "seller_profile_id" INTEGER NOT NULL,
  "group" sellerprofilechangegroup NOT NULL,
  "status" sellerprofilechangestatus NOT NULL,
  "proposed_json" JSONB NOT NULL,
  "applied_json" JSONB,
  "baseline_json" JSONB NOT NULL,
  "admin_note" TEXT,
  "submission_count" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "decided_at" TIMESTAMPTZ,
  "decided_by_user_id" INTEGER
);

CREATE TABLE "seller_profile_change_request_event" (
  "id" UUID PRIMARY KEY,
  "change_request_id" UUID NOT NULL,
  "kind" sellerprofilechangeeventkind NOT NULL,
  "actor_user_id" INTEGER NOT NULL,
  "actor_role" VARCHAR(16) NOT NULL,
  "payload_json" JSONB,
  "note" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL
);

-- Dev Mailbox (development-only capture of outbound email/SMS; see
-- core/dev_mailbox.py + api/dev_inbox.py). Rows only written when
-- ENVIRONMENT=development.
CREATE TABLE "dev_email" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "to_email" VARCHAR NOT NULL,
  "subject" VARCHAR NOT NULL,
  "body_text" VARCHAR NOT NULL,
  "body_html" VARCHAR,
  "reply_to" VARCHAR,
  "category" VARCHAR,
  "provider" VARCHAR NOT NULL
);

CREATE TABLE "dev_sms" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "to_phone" VARCHAR NOT NULL,
  "body" VARCHAR NOT NULL,
  "category" VARCHAR,
  "provider" VARCHAR NOT NULL
);

CREATE TABLE "dev_whatsapp" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "to_phone" VARCHAR NOT NULL,
  "body" VARCHAR NOT NULL,
  "template" VARCHAR,
  "category" VARCHAR,
  "provider" VARCHAR NOT NULL
);

-- Admin-published, versioned policy content. Current = highest version per
-- kind. `published_by` has no FK so history survives admin deletion.
CREATE TABLE "policydocument" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "kind" policykind NOT NULL,
  "version" INTEGER NOT NULL,
  "body" VARCHAR NOT NULL,
  "published_by" INTEGER
);

-- Append-only consent log: which effective policy version (e.g. 't1-p1') a
-- user accepted, and when (created_at).
CREATE TABLE "policyacceptance" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "user_id" INTEGER NOT NULL,
  "policy_version" VARCHAR NOT NULL
);

-- Visitor-submitted seller/store onboarding lead, captured from the
-- deliverability fallback. `submitted_by_user_id` has no FK so lead history
-- survives user deletion. `area_*` records the visitor location at submit.
CREATE TABLE "seller_onboarding_request" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "store_name" VARCHAR(120) NOT NULL,
  "contact_phone" VARCHAR(20) NOT NULL,
  "contact_email" VARCHAR(254) NOT NULL,
  "contact_address" VARCHAR(500) NOT NULL,
  "preferred_categories" VARCHAR(300),
  "area_lat" DOUBLE PRECISION,
  "area_lng" DOUBLE PRECISION,
  "area_label" VARCHAR(120),
  "source" VARCHAR(16),
  "submitted_by_user_id" INTEGER,
  "status" onboardingrequeststatus NOT NULL
);

-- Platform-fee model: global settings, per-service config, subscription plan
-- prices, and the per-(store, service) fee arrangement + its payments/events.
CREATE TABLE "platform_fee_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "grace_period_days" INTEGER NOT NULL,
  "expiry_reminder_start_days" INTEGER NOT NULL,
  "pending_payment_protect_days" INTEGER NOT NULL,
  "bank_account_name" VARCHAR(140),
  "bank_account_number" VARCHAR(40),
  "bank_ifsc" VARCHAR(20),
  "upi_id" VARCHAR(100),
  "qr_image_url" VARCHAR(500),
  "qr_storage_key" VARCHAR(300),
  "gstin" VARCHAR(20)
);

CREATE TABLE "service_fee_config" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "service_id" INTEGER NOT NULL,
  "freebie_enabled" BOOLEAN NOT NULL,
  "freebie_default_days" INTEGER NOT NULL,
  "subscription_enabled" BOOLEAN NOT NULL,
  "order_value_enabled" BOOLEAN NOT NULL,
  "order_value_percent" DOUBLE PRECISION NOT NULL,
  "order_value_min_deposit" DOUBLE PRECISION NOT NULL,
  "order_value_billing_day" INTEGER NOT NULL,
  "pay_per_txn_enabled" BOOLEAN NOT NULL,
  "pay_per_txn_fee" DOUBLE PRECISION NOT NULL,
  "pay_per_txn_min_deposit" DOUBLE PRECISION NOT NULL,
  "pay_per_txn_low_balance_threshold" DOUBLE PRECISION NOT NULL,
  CONSTRAINT "uq_service_fee_config_service" UNIQUE ("service_id")
);

CREATE TABLE "service_subscription_plan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "service_id" INTEGER NOT NULL,
  "duration_months" INTEGER NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  CONSTRAINT "uq_service_subscription_plan" UNIQUE ("service_id", "duration_months")
);

CREATE TABLE "fee_arrangement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "store_id" INTEGER NOT NULL,
  "service_id" INTEGER NOT NULL,
  "model" feemodel NOT NULL,
  "status" arrangementstatus NOT NULL,
  "valid_until" DATE,
  "subscription_duration_months" INTEGER,
  "price_snapshot" DOUBLE PRECISION,
  "security_deposit_amount" DOUBLE PRECISION NOT NULL,
  "balance" DOUBLE PRECISION NOT NULL,
  "auto_renew" BOOLEAN NOT NULL,
  "cancel_requested" BOOLEAN NOT NULL,
  "queued_model" feemodel,
  "queued_duration_months" INTEGER,
  "queued_effective_date" DATE,
  "pending_since" TIMESTAMPTZ,
  "last_reminder_sent_on" DATE,
  "suspended_at" TIMESTAMPTZ,
  "suspended_reason" VARCHAR(200),
  CONSTRAINT "uq_fee_arrangement_store_service" UNIQUE ("store_id", "service_id")
);

CREATE TABLE "fee_payment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "arrangement_id" INTEGER NOT NULL,
  "kind" feepaymentkind NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "status" feepaymentstatus NOT NULL,
  "seller_note" VARCHAR(200),
  "confirmed_by_admin_id" INTEGER,
  "confirmed_at" TIMESTAMPTZ,
  "reject_reason" VARCHAR(200)
);

CREATE TABLE "fee_event" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "arrangement_id" INTEGER NOT NULL,
  "event_type" feeeventtype NOT NULL,
  "amount_delta" DOUBLE PRECISION,
  "note" VARCHAR(300),
  "actor" VARCHAR(60)
);

-- Indexes -----------------------------------------------------------------

CREATE UNIQUE INDEX "ix_user_email" ON "user" ("email");

CREATE UNIQUE INDEX "ix_customerprofile_user" ON "customerprofile" ("user_id");
CREATE UNIQUE INDEX "ix_customerprofile_phone" ON "customerprofile" ("phone");

CREATE UNIQUE INDEX "ix_adminprofile_user" ON "adminprofile" ("user_id");
CREATE UNIQUE INDEX "ix_adminprofile_phone" ON "adminprofile" ("phone");

CREATE UNIQUE INDEX "uq_sellerprofile_user" ON "sellerprofile" ("user_id");
CREATE UNIQUE INDEX "ix_sellerprofile_phone" ON "sellerprofile" ("phone");
CREATE INDEX "ix_sellerprofile_business_address_id"
  ON "sellerprofile" ("business_address_id");

CREATE UNIQUE INDEX "uq_sellerprofile_service"
  ON "sellerprofile_service" ("seller_profile_id", "service_id");
CREATE INDEX "ix_sellerprofile_service_seller_profile_id"
  ON "sellerprofile_service" ("seller_profile_id");
CREATE INDEX "ix_sellerprofile_service_service_id"
  ON "sellerprofile_service" ("service_id");

CREATE UNIQUE INDEX "uq_customeraddress_customer_address"
  ON "customeraddress" ("customer_profile_id", "address_id");
CREATE INDEX "ix_customeraddress_customer_profile_id"
  ON "customeraddress" ("customer_profile_id");
-- Partial unique index: only one default address per customer.
CREATE UNIQUE INDEX "uq_customeraddress_one_default"
  ON "customeraddress" ("customer_profile_id")
  WHERE is_default = true;

CREATE INDEX "ix_address_geo" ON "address" USING GIST ("geo");

CREATE UNIQUE INDEX "ix_service_slug" ON "service" ("slug");
CREATE UNIQUE INDEX "uq_service_translation"
  ON "service_translation" ("service_id", "language_code");
-- Trigram GIN indexes for slug + translation name search (pg_trgm).
CREATE INDEX "ix_service_slug_trgm"
  ON "service" USING GIN ("slug" gin_trgm_ops);
CREATE INDEX "ix_service_translation_name_trgm"
  ON "service_translation" USING GIN ("name" gin_trgm_ops);

CREATE INDEX "ix_category_service_id" ON "category" ("service_id");
CREATE INDEX "ix_category_is_active" ON "category" ("is_active");
CREATE INDEX "ix_category_service_active"
  ON "category" ("service_id", "is_active");
-- Partial unique: slug unique per service only while active. Replaces the
-- old uq_category_service_slug which forced a global per-service unique.
CREATE UNIQUE INDEX "uq_category_service_slug_active"
  ON "category" ("service_id", "slug")
  WHERE is_active = TRUE;
CREATE INDEX "ix_category_slug_trgm"
  ON "category" USING GIN ("slug" gin_trgm_ops);
CREATE UNIQUE INDEX "uq_category_translation"
  ON "category_translation" ("category_id", "language_code");
CREATE INDEX "ix_category_translation_name_trgm"
  ON "category_translation" USING GIN ("name" gin_trgm_ops);

CREATE INDEX "ix_subcategory_category_id" ON "subcategory" ("category_id");
CREATE INDEX "ix_subcategory_is_active" ON "subcategory" ("is_active");
CREATE INDEX "ix_subcategory_category_active"
  ON "subcategory" ("category_id", "is_active");
CREATE UNIQUE INDEX "uq_subcategory_category_slug_active"
  ON "subcategory" ("category_id", "slug")
  WHERE is_active = TRUE;
CREATE INDEX "ix_subcategory_slug_trgm"
  ON "subcategory" USING GIN ("slug" gin_trgm_ops);
CREATE UNIQUE INDEX "uq_subcategory_translation"
  ON "subcategory_translation" ("subcategory_id", "language_code");
CREATE INDEX "ix_subcategory_translation_name_trgm"
  ON "subcategory_translation" USING GIN ("name" gin_trgm_ops);

-- ix_masterproduct_slug is non-unique after migration eeb39ac86872; slug
-- uniqueness is now enforced per-subcategory via the partial unique below.
CREATE INDEX "ix_masterproduct_slug" ON "masterproduct" ("slug");
CREATE INDEX "ix_masterproduct_subcategory_id"
  ON "masterproduct" ("subcategory_id");
CREATE INDEX "ix_masterproduct_is_active" ON "masterproduct" ("is_active");
CREATE INDEX "ix_masterproduct_subcategory_active"
  ON "masterproduct" ("subcategory_id", "is_active");
CREATE UNIQUE INDEX "uq_masterproduct_subcategory_slug_active"
  ON "masterproduct" ("subcategory_id", "slug")
  WHERE is_active = TRUE;
CREATE INDEX "ix_masterproduct_slug_trgm"
  ON "masterproduct" USING GIN ("slug" gin_trgm_ops);
CREATE UNIQUE INDEX "uq_masterproduct_translation"
  ON "masterproduct_translation" ("master_product_id", "language_code");
CREATE INDEX "ix_masterproduct_translation_name_trgm"
  ON "masterproduct_translation" USING GIN ("name" gin_trgm_ops);
CREATE INDEX "ix_masterproductimage_master_product_id"
  ON "masterproductimage" ("master_product_id");

CREATE UNIQUE INDEX "uq_store_seller_profile" ON "store" ("seller_profile_id");
CREATE INDEX "ix_store_name" ON "store" ("name");
CREATE INDEX "ix_store_seller_profile_id" ON "store" ("seller_profile_id");
CREATE INDEX "ix_store_address_id" ON "store" ("address_id");

CREATE UNIQUE INDEX "uq_store_product" ON "storeinventory" ("store_id", "product_id");

-- Unique key now includes service_id: a single store can hold multiple
-- sub-baskets (Grocery, Food, Pharmacy, …) for the same customer.
CREATE UNIQUE INDEX "uq_cart_customer_store_service"
  ON "cart" ("customer_profile_id", "store_id", "service_id");
CREATE INDEX "ix_cart_service_id" ON "cart" ("service_id");
CREATE UNIQUE INDEX "uq_cartitem_cart_inventory"
  ON "cartitem" ("cart_id", "inventory_id");

CREATE INDEX "ix_order_customer_profile_id" ON "order" ("customer_profile_id");
CREATE INDEX "ix_order_store_id" ON "order" ("store_id");
CREATE INDEX "ix_order_service_id" ON "order" ("service_id");
CREATE INDEX "ix_order_status" ON "order" ("status");
CREATE INDEX "ix_order_customer_status" ON "order" ("customer_profile_id", "status");
CREATE INDEX "ix_order_store_status" ON "order" ("store_id", "status");

CREATE UNIQUE INDEX "uq_orderitem_order_inventory"
  ON "orderitem" ("order_id", "inventory_id");

CREATE INDEX "ix_payment_order_id" ON "payment" ("order_id");
CREATE UNIQUE INDEX "ix_payment_gateway_txn_id" ON "payment" ("gateway_txn_id");

CREATE UNIQUE INDEX "ix_delivery_order_id" ON "delivery" ("order_id");

CREATE INDEX "ix_review_customer_profile_id" ON "review" ("customer_profile_id");
CREATE INDEX "ix_review_product_id" ON "review" ("product_id");
CREATE INDEX "ix_review_store_id" ON "review" ("store_id");
-- Partial unique: an order has at most one review. Product/store reviews
-- without an order_id remain unconstrained.
CREATE UNIQUE INDEX "uq_review_order_id"
  ON "review" ("order_id")
  WHERE order_id IS NOT NULL;

CREATE UNIQUE INDEX "uq_favorite_customer_product"
  ON "favorite" ("customer_profile_id", "product_id");
-- Recent-first listing index for /account/favorites and dashboard rail.
CREATE INDEX "ix_favorite_customer_created"
  ON "favorite" ("customer_profile_id", "created_at" DESC);

CREATE INDEX "ix_search_query_log_created_at"
  ON "search_query_log" ("created_at");
CREATE UNIQUE INDEX "ix_search_query_log_query_id"
  ON "search_query_log" ("query_id");

CREATE INDEX "ix_admin_action_log_admin_user_id"
  ON "admin_action_log" ("admin_user_id");
CREATE INDEX "ix_admin_action_log_seller_created"
  ON "admin_action_log" ("target_seller_id", "created_at");

CREATE INDEX "ix_pushsubscription_customer_profile_id"
  ON "pushsubscription" ("customer_profile_id");
CREATE UNIQUE INDEX "ix_pushsubscription_endpoint"
  ON "pushsubscription" ("endpoint");

CREATE INDEX "ix_notification_customer_profile_id"
  ON "notification" ("customer_profile_id");
CREATE INDEX "ix_notification_customer_created"
  ON "notification" ("customer_profile_id", "created_at");
CREATE INDEX "ix_notification_seller_profile_id"
  ON "notification" ("seller_profile_id");
CREATE INDEX "ix_notification_seller_created"
  ON "notification" ("seller_profile_id", "created_at");

CREATE INDEX "ix_seller_profile_change_request_seller_profile_id"
  ON "seller_profile_change_request" ("seller_profile_id");
CREATE INDEX "ix_seller_profile_cr_seller_created"
  ON "seller_profile_change_request" ("seller_profile_id", "created_at");
-- Partial unique: at most one open (submitted/changes_requested) CR per
-- (seller, group). Approved/rejected/withdrawn rows are unconstrained.
CREATE UNIQUE INDEX "uq_seller_profile_cr_open"
  ON "seller_profile_change_request" ("seller_profile_id", "group")
  WHERE status IN ('submitted', 'changes_requested');

CREATE INDEX "ix_seller_profile_change_request_event_change_request_id"
  ON "seller_profile_change_request_event" ("change_request_id");
CREATE INDEX "ix_seller_profile_cr_event_cr_created"
  ON "seller_profile_change_request_event" ("change_request_id", "created_at");

CREATE INDEX "ix_dev_email_to_email" ON "dev_email" ("to_email");
CREATE INDEX "ix_dev_email_category" ON "dev_email" ("category");
CREATE INDEX "ix_dev_sms_to_phone" ON "dev_sms" ("to_phone");
CREATE INDEX "ix_dev_sms_category" ON "dev_sms" ("category");
CREATE INDEX "ix_dev_whatsapp_to_phone" ON "dev_whatsapp" ("to_phone");
CREATE INDEX "ix_dev_whatsapp_template" ON "dev_whatsapp" ("template");
CREATE INDEX "ix_dev_whatsapp_category" ON "dev_whatsapp" ("category");

CREATE UNIQUE INDEX "uq_policydocument_kind_version"
  ON "policydocument" ("kind", "version");

CREATE INDEX "ix_policyacceptance_user_id"
  ON "policyacceptance" ("user_id");
CREATE UNIQUE INDEX "uq_policyacceptance_user_version"
  ON "policyacceptance" ("user_id", "policy_version");

CREATE INDEX "ix_seller_onboarding_request_submitted_by_user_id"
  ON "seller_onboarding_request" ("submitted_by_user_id");

CREATE INDEX "ix_service_fee_config_service_id"
  ON "service_fee_config" ("service_id");

CREATE INDEX "ix_service_subscription_plan_service_id"
  ON "service_subscription_plan" ("service_id");

CREATE INDEX "ix_fee_arrangement_store_id" ON "fee_arrangement" ("store_id");
CREATE INDEX "ix_fee_arrangement_service_id" ON "fee_arrangement" ("service_id");
CREATE INDEX "ix_fee_arrangement_status" ON "fee_arrangement" ("status");

CREATE INDEX "ix_fee_payment_arrangement_id" ON "fee_payment" ("arrangement_id");
CREATE INDEX "ix_fee_payment_status" ON "fee_payment" ("status");

CREATE INDEX "ix_fee_event_arrangement_id" ON "fee_event" ("arrangement_id");

-- Comments ----------------------------------------------------------------

COMMENT ON TABLE "language" IS
  'Seed: en/English/English, hi/Hindi/हिन्दी, mr/Marathi/मराठी, gu/Gujarati/ગુજરાતી, pa/Punjabi/ਪੰਜਾਬੀ. LanguageCode app-enum: en, hi, mr, gu, pa.';

COMMENT ON TABLE "customeraddress" IS
  'Partial unique index uq_customeraddress_one_default enforces one default address per customer (WHERE is_default = true).';

COMMENT ON TABLE "service" IS
  'Top-level vertical: Groceries, Pharmacy, Restaurant, etc. Display name/description live in service_translation.';

COMMENT ON COLUMN "address"."geo" IS
  'Generated STORED geography(Point, 4326) column derived from latitude/longitude. SQLModel does not declare it; reads happen via raw SQL. Indexed by GiST (ix_address_geo).';

COMMENT ON TABLE "cart" IS
  'Unique key (customer_profile_id, store_id, service_id) — a single store can hold multiple sub-baskets (Grocery, Food, Pharmacy, …) for the same customer.';

COMMENT ON TABLE "order" IS
  'Totals are intentionally denormalized for immutable financial history. delivery_address_snapshot captures a human-readable copy of the address at order time. service_id + service_name_snapshot freeze the service vertical so order history survives later catalog edits.';

COMMENT ON TABLE "review" IS
  'CHECK ck_review_one_target: exactly one of product_id / store_id must be set. CHECK ck_review_rating_range: rating in 1..5. Partial unique uq_review_order_id allows at most one review per order.';

COMMENT ON TABLE "category" IS
  'Slug uniqueness is enforced per-service AND only while is_active (uq_category_service_slug_active). Inactive duplicates are allowed so soft-deleted categories can be recreated.';

COMMENT ON TABLE "subcategory" IS
  'Slug uniqueness is enforced per-category AND only while is_active (uq_subcategory_category_slug_active).';

COMMENT ON TABLE "masterproduct" IS
  'Slug uniqueness is enforced per-subcategory AND only while is_active (uq_masterproduct_subcategory_slug_active). The global slug-unique index was dropped in migration eeb39ac86872.';

COMMENT ON TABLE "search_query_log" IS
  'Append-only log of search queries + click-throughs. user_id/store_id FKs use ON DELETE SET NULL so analytics survive row deletion.';

COMMENT ON TABLE "admin_action_log" IS
  'Audit trail for admin seller-supervisor actions. target_id has NO FK so deleted-row history is preserved across inventory/order/store/seller deletes.';

COMMENT ON TABLE "pushsubscription" IS
  'Web Push (VAPID) device subscriptions, customers only. Unique on endpoint; 404/410 responses prune the row. Opt-in is per-device.';

COMMENT ON TABLE "notification" IS
  'In-app notification feed (navbar bell). Recipient is exactly one of customer_profile_id/seller_profile_id (ck_notification_one_recipient). type=OrderStatus/DeliveryOtp for customers, FeeActivated/FeeExpiring/FeeSuspended for sellers; status_value holds the order status string. Push fan-out is best-effort and never blocks the order path.';

COMMENT ON TABLE "sellerprofile_service" IS
  'M:N junction: seller offers one or more services. Carries per-service config: free_delivery_threshold + delivery_fee (flat fee charged below the threshold), delivery ETA window, and pause (holiday mode). Replaces the dropped sellerprofile.business_category column.';

COMMENT ON TABLE "store" IS
  'pin_confirmed=false until seller confirms the map pin. delivery_radius_km gates serviceability (PostGIS ST_DWithin). is_paused/pause_reason/paused_until drive store-wide holiday mode.';

COMMENT ON TABLE "seller_profile_change_request" IS
  'Approved-seller self-service profile edits, grouped by domain (identity/address/legal/banking/services/store_basics). Partial unique uq_seller_profile_cr_open allows at most one open CR per (seller, group).';

COMMENT ON TABLE "seller_profile_change_request_event" IS
  'Append-only event log per change request (submitted/resubmitted/decided). FK to the CR is ON DELETE CASCADE.';

COMMENT ON TABLE "platform_fee_settings" IS
  'Single-row global platform-fee configuration: grace/reminder windows and the bank/UPI/QR payout details shown to sellers.';

COMMENT ON TABLE "service_fee_config" IS
  'Per-service platform-fee model toggles + parameters (freebie, subscription, order-value-percent, pay-per-transaction). One row per service (uq_service_fee_config_service).';

COMMENT ON TABLE "service_subscription_plan" IS
  'Per-service subscription plan prices by duration (3/6/12 months). Unique per (service_id, duration_months).';

COMMENT ON TABLE "fee_arrangement" IS
  'Per-(store, service) fee arrangement: active model, balance/deposit, queued model-change, and grace/suspension state. Unique per (store_id, service_id).';

COMMENT ON TABLE "fee_payment" IS
  'Seller-reported payments (subscription fee, security deposit, pay-per-txn top-up, order-value invoice) against a fee_arrangement, admin-confirmed or rejected.';

COMMENT ON TABLE "fee_event" IS
  'Append-only audit trail of fee_arrangement lifecycle events (created, activated, suspended, payments, balance adjustments, etc).';

-- Foreign keys ------------------------------------------------------------

ALTER TABLE "user"
  ADD FOREIGN KEY ("preferred_language") REFERENCES "language" ("code");

ALTER TABLE "customerprofile"
  ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "adminprofile"
  ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "sellerprofile"
  ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "sellerprofile"
  ADD FOREIGN KEY ("business_address_id") REFERENCES "address" ("id");

ALTER TABLE "sellerprofile_service"
  ADD FOREIGN KEY ("seller_profile_id") REFERENCES "sellerprofile" ("id");
ALTER TABLE "sellerprofile_service"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");

ALTER TABLE "customeraddress"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "customeraddress"
  ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id");

ALTER TABLE "service_translation"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");
ALTER TABLE "service_translation"
  ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code");

ALTER TABLE "category"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");
ALTER TABLE "category_translation"
  ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");
ALTER TABLE "category_translation"
  ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code");

ALTER TABLE "subcategory"
  ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");
ALTER TABLE "subcategory_translation"
  ADD FOREIGN KEY ("subcategory_id") REFERENCES "subcategory" ("id");
ALTER TABLE "subcategory_translation"
  ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code");

ALTER TABLE "masterproduct"
  ADD FOREIGN KEY ("subcategory_id") REFERENCES "subcategory" ("id");
ALTER TABLE "masterproduct_translation"
  ADD FOREIGN KEY ("master_product_id") REFERENCES "masterproduct" ("id");
ALTER TABLE "masterproduct_translation"
  ADD FOREIGN KEY ("language_code") REFERENCES "language" ("code");
ALTER TABLE "masterproductimage"
  ADD FOREIGN KEY ("master_product_id") REFERENCES "masterproduct" ("id") ON DELETE CASCADE;

ALTER TABLE "store"
  ADD FOREIGN KEY ("seller_profile_id") REFERENCES "sellerprofile" ("id");
ALTER TABLE "store"
  ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id");

ALTER TABLE "storeinventory"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
ALTER TABLE "storeinventory"
  ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id");

ALTER TABLE "cart"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "cart"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
ALTER TABLE "cart"
  ADD CONSTRAINT "fk_cart_service"
  FOREIGN KEY ("service_id") REFERENCES "service" ("id");

ALTER TABLE "cartitem"
  ADD FOREIGN KEY ("cart_id") REFERENCES "cart" ("id");
ALTER TABLE "cartitem"
  ADD FOREIGN KEY ("inventory_id") REFERENCES "storeinventory" ("id");

ALTER TABLE "order"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "order"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
ALTER TABLE "order"
  ADD CONSTRAINT "fk_order_service"
  FOREIGN KEY ("service_id") REFERENCES "service" ("id");
ALTER TABLE "order"
  ADD FOREIGN KEY ("delivery_address_id") REFERENCES "address" ("id");

ALTER TABLE "orderitem"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");
ALTER TABLE "orderitem"
  ADD FOREIGN KEY ("inventory_id") REFERENCES "storeinventory" ("id")
  ON DELETE SET NULL;

ALTER TABLE "payment"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "delivery"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "review"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "review"
  ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id");
ALTER TABLE "review"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
ALTER TABLE "review"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "favorite"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "favorite"
  ADD FOREIGN KEY ("product_id") REFERENCES "masterproduct" ("id");

ALTER TABLE "search_query_log"
  ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE SET NULL;
ALTER TABLE "search_query_log"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") ON DELETE SET NULL;

ALTER TABLE "admin_action_log"
  ADD FOREIGN KEY ("admin_user_id") REFERENCES "user" ("id");
ALTER TABLE "admin_action_log"
  ADD FOREIGN KEY ("target_seller_id") REFERENCES "sellerprofile" ("id");

ALTER TABLE "pushsubscription"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");

ALTER TABLE "notification"
  ADD FOREIGN KEY ("customer_profile_id") REFERENCES "customerprofile" ("id");
ALTER TABLE "notification"
  ADD CONSTRAINT "fk_notification_seller_profile"
  FOREIGN KEY ("seller_profile_id") REFERENCES "sellerprofile" ("id");
ALTER TABLE "notification"
  ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "seller_profile_change_request"
  ADD FOREIGN KEY ("seller_profile_id") REFERENCES "sellerprofile" ("id");
ALTER TABLE "seller_profile_change_request"
  ADD FOREIGN KEY ("decided_by_user_id") REFERENCES "user" ("id");

ALTER TABLE "seller_profile_change_request_event"
  ADD FOREIGN KEY ("change_request_id")
  REFERENCES "seller_profile_change_request" ("id") ON DELETE CASCADE;
ALTER TABLE "seller_profile_change_request_event"
  ADD FOREIGN KEY ("actor_user_id") REFERENCES "user" ("id");

ALTER TABLE "policyacceptance"
  ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "service_fee_config"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");

ALTER TABLE "service_subscription_plan"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");

ALTER TABLE "fee_arrangement"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
ALTER TABLE "fee_arrangement"
  ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");

ALTER TABLE "fee_payment"
  ADD FOREIGN KEY ("arrangement_id") REFERENCES "fee_arrangement" ("id");
ALTER TABLE "fee_payment"
  ADD FOREIGN KEY ("confirmed_by_admin_id") REFERENCES "user" ("id");

ALTER TABLE "fee_event"
  ADD FOREIGN KEY ("arrangement_id") REFERENCES "fee_arrangement" ("id");

-- ── Referrals ────────────────────────────────────────────────────────────
-- User-initiated onboarding of a new customer or seller. The row is its own
-- audit record (source, reviewer, outcome). FK-less id columns (source_user_id,
-- reviewed_by_admin_id, activated_user_id) so history survives user deletion.
CREATE TABLE "referral_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "require_admin_approval" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "referral" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "source_user_id" INTEGER NOT NULL,
  "source_role" userrole NOT NULL,
  "target_role" referraltargetrole NOT NULL,
  "invitee_name" VARCHAR(120) NOT NULL,
  "invitee_phone" VARCHAR(20),
  "invitee_email" VARCHAR(254),
  "location_state" VARCHAR(80) NOT NULL,
  "location_area" VARCHAR(160) NOT NULL,
  "status" referralstatus NOT NULL DEFAULT 'pending_review',
  "rejection_reason" VARCHAR(300),
  "reviewed_by_admin_id" INTEGER,
  "reviewed_at" TIMESTAMPTZ,
  "invite_expires_at" TIMESTAMPTZ,
  "activated_user_id" INTEGER,
  "activated_at" TIMESTAMPTZ
);

CREATE INDEX "ix_referral_source_user_id" ON "referral" ("source_user_id");
CREATE INDEX "ix_referral_source_status" ON "referral" ("source_user_id", "status");
CREATE INDEX "ix_referral_status" ON "referral" ("status");
-- Block a second OPEN referral for the same contact; rejected/expired coexist.
CREATE UNIQUE INDEX "uq_referral_open_email" ON "referral" ("invitee_email")
  WHERE "status" IN ('pending_review', 'approved') AND "invitee_email" IS NOT NULL;
CREATE UNIQUE INDEX "uq_referral_open_phone" ON "referral" ("invitee_phone")
  WHERE "status" IN ('pending_review', 'approved') AND "invitee_phone" IS NOT NULL;

-- Credit customers (Spec 2 R2): admin per-seller gate + cap, the revolving
-- account (denormalized outstanding_balance), and the append-only ledger.
CREATE TABLE "seller_credit_config" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "seller_profile_id" INTEGER NOT NULL REFERENCES "sellerprofile" ("id"),
  "credit_enabled" BOOLEAN NOT NULL DEFAULT false,
  "max_limit_per_customer" DOUBLE PRECISION NOT NULL DEFAULT 0,
  CONSTRAINT "uq_seller_credit_config_seller" UNIQUE ("seller_profile_id")
);
CREATE INDEX "ix_seller_credit_config_seller_profile_id" ON "seller_credit_config" ("seller_profile_id");

CREATE TABLE "credit_account" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "seller_profile_id" INTEGER NOT NULL REFERENCES "sellerprofile" ("id"),
  "customer_profile_id" INTEGER NOT NULL REFERENCES "customerprofile" ("id"),
  "credit_limit" DOUBLE PRECISION NOT NULL,
  "outstanding_balance" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "status" creditaccountstatus NOT NULL DEFAULT 'active',
  "granted_by_user_id" INTEGER NOT NULL,
  "last_notified_threshold" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "uq_credit_account_pair" UNIQUE ("seller_profile_id", "customer_profile_id")
);
CREATE INDEX "ix_credit_account_seller_profile_id" ON "credit_account" ("seller_profile_id");
CREATE INDEX "ix_credit_account_customer" ON "credit_account" ("customer_profile_id");

CREATE TABLE "credit_ledger_entry" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "credit_account_id" INTEGER NOT NULL REFERENCES "credit_account" ("id"),
  "entry_type" creditentrytype NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "order_id" INTEGER REFERENCES "order" ("id"),
  "balance_after" DOUBLE PRECISION NOT NULL,
  "note" VARCHAR(300),
  "recorded_by_user_id" INTEGER
);
CREATE INDEX "ix_credit_ledger_entry_credit_account_id" ON "credit_ledger_entry" ("credit_account_id");
CREATE INDEX "ix_credit_ledger_account_created" ON "credit_ledger_entry" ("credit_account_id", "created_at");
