/**
 * Khana Bazaar — geo helpers.
 *
 * Thin wrappers over /api/v1/geo/* endpoints. Wire types mirror
 * `backend/app/src/app/schemas/geo.py`.
 */

import { get, post } from "@/lib/api";

export interface GeoComponent {
  long_name: string;
  short_name: string;
  types: string[];
}

export interface GeoPrediction {
  place_id: string;
  description: string;
}

export interface GeoPlace {
  place_id: string;
  formatted_address: string;
  latitude: number;
  longitude: number;
  components: GeoComponent[];
}

export interface ServiceabilityResult {
  serviceable: boolean;
  store_count?: number | null;
}

/** Generate a fresh Google Places session token. Call once per address-entry
 *  session (each modal open / each new address being typed). The token is
 *  reused across every autocomplete request and the final placeDetails call,
 *  then regenerated by the caller after placeDetails returns — that's the
 *  contract Google's billing uses to charge a session as one unit. */
export const newSessionToken = (): string =>
  typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);

export async function autocomplete(
  q: string, sessionToken: string,
): Promise<{ predictions: GeoPrediction[] }> {
  return get(
    `/api/v1/geo/autocomplete?q=${encodeURIComponent(q)}` +
      `&session_token=${encodeURIComponent(sessionToken)}`,
  );
}

export async function placeDetails(
  placeId: string, sessionToken: string,
): Promise<GeoPlace> {
  return get(
    `/api/v1/geo/place/${encodeURIComponent(placeId)}?session_token=${encodeURIComponent(sessionToken)}`,
  );
}

export async function reverseGeocode(
  lat: number, lng: number,
): Promise<GeoPlace> {
  return get(`/api/v1/geo/reverse?lat=${lat}&lng=${lng}`);
}

export async function checkServiceability(
  lat: number, lng: number, storeId?: number,
): Promise<ServiceabilityResult> {
  return post("/api/v1/geo/serviceability", {
    lat,
    lng,
    ...(storeId !== undefined ? { store_id: storeId } : {}),
  });
}

/** Truncate a long formatted address to fit a navbar chip. */
export function truncateLabel(text: string, max = 40): string {
  return text.length <= max ? text : `${text.slice(0, max - 1)}…`;
}
